services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    volumes:
      - .:/app
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    command:
            poetry fastapi run ./python_o_bom_candidato/app.py 
    #command: uvicorn app.python_o_bom_candidato.app:app --host 0.0.0.0 --port 8000
    #command: python -m uvicorn app.python_o_bom_candidato.app:app --host 0.0.0.0 --port 8000

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
